# Generated by Django 4.2.7 on 2023-11-27 13:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('director', models.CharField(blank=True, max_length=200, null=True)),
                ('actors', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('genre', models.ManyToManyField(blank=True, to='movies.genre')),
            ],
        ),
    ]
